"""cascadedel

Revision ID: 34c60a91968d
Revises: 0ee666e5b43b
Create Date: 2024-04-28 16:07:58.634478

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34c60a91968d"
down_revision: Union[str, None] = "0ee666e5b43b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("forms_user_id_fkey", "forms", type_="foreignkey")
    op.create_foreign_key(
        None, "forms", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("options_question_id_fkey", "options", type_="foreignkey")
    op.create_foreign_key(
        None, "options", "questions", ["question_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("questions_form_id_fkey", "questions", type_="foreignkey")
    op.create_foreign_key(
        None, "questions", "forms", ["form_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "radioanswers_option_id_fkey", "radioanswers", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "radioanswers", "options", ["option_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(
        "textanswers_question_id_fkey", "textanswers", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "textanswers", "questions", ["question_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=32), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(length=32), nullable=True
    )
    op.drop_constraint(None, "textanswers", type_="foreignkey")
    op.create_foreign_key(
        "textanswers_question_id_fkey",
        "textanswers",
        "questions",
        ["question_id"],
        ["id"],
    )
    op.drop_constraint(None, "radioanswers", type_="foreignkey")
    op.create_foreign_key(
        "radioanswers_option_id_fkey", "radioanswers", "options", ["option_id"], ["id"]
    )
    op.drop_constraint(None, "questions", type_="foreignkey")
    op.create_foreign_key(
        "questions_form_id_fkey", "questions", "forms", ["form_id"], ["id"]
    )
    op.drop_constraint(None, "options", type_="foreignkey")
    op.create_foreign_key(
        "options_question_id_fkey", "options", "questions", ["question_id"], ["id"]
    )
    op.drop_constraint(None, "forms", type_="foreignkey")
    op.create_foreign_key("forms_user_id_fkey", "forms", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###
