"""form+Q update

Revision ID: 3cdeb064fa5f
Revises: 6ed69bffa6f1
Create Date: 2024-04-26 22:27:50.889101

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3cdeb064fa5f"
down_revision: Union[str, None] = "6ed69bffa6f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkboxanswers",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("checkbox_answers")
    op.add_column(
        "checkbox_answers_association",
        sa.Column("checkboxanswer_id", sa.Integer(), nullable=False),
    )
    op.drop_constraint(
        "checkbox_answers_association_checkbox_answer_id_fkey",
        "checkbox_answers_association",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "checkbox_answers_association",
        "checkboxanswers",
        ["checkboxanswer_id"],
        ["id"],
    )
    op.drop_column("checkbox_answers_association", "id")
    op.drop_column("checkbox_answers_association", "checkbox_answer_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "checkbox_answers_association",
        sa.Column(
            "checkbox_answer_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "checkbox_answers_association",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.drop_constraint(None, "checkbox_answers_association", type_="foreignkey")
    op.create_foreign_key(
        "checkbox_answers_association_checkbox_answer_id_fkey",
        "checkbox_answers_association",
        "checkbox_answers",
        ["checkbox_answer_id"],
        ["id"],
    )
    op.drop_column("checkbox_answers_association", "checkboxanswer_id")
    op.create_table(
        "checkbox_answers",
        sa.Column("question_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], name="checkbox_answers_question_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="checkbox_answers_pkey"),
    )
    op.drop_table("checkboxanswers")
    # ### end Alembic commands ###
