"""Answers+associat

Revision ID: 6ed69bffa6f1
Revises: 565903cda898
Create Date: 2024-04-25 22:22:59.159702

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ed69bffa6f1"
down_revision: Union[str, None] = "565903cda898"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkbox_answers",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "textanswers",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "checkbox_answers_association",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("checkbox_answer_id", sa.Integer(), nullable=True),
        sa.Column("option_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["checkbox_answer_id"],
            ["checkbox_answers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["option_id"],
            ["options.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "radioanswers",
        sa.Column("option_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["option_id"],
            ["options.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("radioanswers")
    op.drop_table("checkbox_answers_association")
    op.drop_table("textanswers")
    op.drop_table("checkbox_answers")
    # ### end Alembic commands ###
