"""midcon

Revision ID: 839c7ffef6b1
Revises: 6ed69bffa6f1
Create Date: 2024-04-27 14:53:28.182313

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "839c7ffef6b1"
down_revision: Union[str, None] = "6ed69bffa6f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkboxanswers",
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "checkbox_answers_association",
        sa.Column("checkboxanswer_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        None,
        "checkbox_answers_association",
        "checkboxanswers",
        ["checkboxanswer_id"],
        ["id"],
    )
    op.drop_column("checkbox_answers_association", "checkbox_answer_id")
    op.drop_column("checkbox_answers_association", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "checkbox_answers_association",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.add_column(
        "checkbox_answers_association",
        sa.Column(
            "checkbox_answer_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "checkbox_answers_association", type_="foreignkey")
    op.drop_column("checkbox_answers_association", "checkboxanswer_id")
    op.drop_table("checkboxanswers")
    # ### end Alembic commands ###
