"""delete qID for ChAnswers

Revision ID: b3550decc84b
Revises: 839c7ffef6b1
Create Date: 2024-04-27 18:15:49.409309

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3550decc84b"
down_revision: Union[str, None] = "839c7ffef6b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "checkboxanswers_question_id_fkey", "checkboxanswers", type_="foreignkey"
    )
    op.drop_column("checkboxanswers", "question_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "checkboxanswers",
        sa.Column("question_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "checkboxanswers_question_id_fkey",
        "checkboxanswers",
        "questions",
        ["question_id"],
        ["id"],
    )
    # ### end Alembic commands ###
